apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "hello.20.231.114.188.nip.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-vs
spec:
  hosts:
  - "hello.20.231.114.188.nip.io"
  gateways:
  - hello-gateway
  http:
  - route:
    - destination:
        host: hello-svc
        port:
          number: 80
---
